name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest tests/test_model.py

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to artifact registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/xgboost-model/xgboost-model:${{github.run_id}}-${{github.run_number}}
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/xgboost-model/xgboost-model:latest

      - name: "Set up GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2.2.1"
        with:
          cluster_name: ${{ vars.GKE_CLUSTER }}
          location: ${{ vars.GKE_ZONE }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
        working-directory: ./k8s

        # Deploy the Docker image to the GKE cluster
      - name: Deploy

        env:
          DEPLOYMENT_NAME: xgboost-model-deployment
          IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/xgboost-model/xgboost-model
          NEW_TAG: ${{ github.run_id }}-${{ github.run_number }}
        run: |-
          ./kustomize edit set image image-placeholder=$IMAGE_NAME:$NEW_TAG

          ./kustomize build . | kubectl apply -f -

          kubectl rollout status deployment/$DEPLOYMENT_NAME

          kubectl get services -o wide
        working-directory: ./k8s
